# Generated by Django 5.1.3 on 2024-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('competition', models.CharField(max_length=100, verbose_name='competition')),
                ('date', models.DateField(verbose_name='date')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('km', models.IntegerField(verbose_name='KM')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('result_time', models.DateField(verbose_name='result_time')),
                ('winner_time', models.DateField(verbose_name='winner_time')),
                ('delta_with_winner', models.DateField(verbose_name='delta_with_winner')),
                ('winner_time_min', models.FloatField(verbose_name='winner_time_min')),
                ('delta_min', models.FloatField(verbose_name='delta_min')),
                ('persent', models.FloatField(verbose_name='persent')),
                ('speed_per_km', models.FloatField(verbose_name='speed_per_km')),
            ],
        ),
    ]
