# Generated by Django 5.1.3 on 2024-12-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='text',
            new_name='text1',
        ),
    ]
